### ISSUE TITLE
Various non standard ASCII codes don't seem to work (lowp)

### ISSUE THREAD

**Issue by paulscottrobson** [ghackwrench/OpenKERNAL#1]
Tried this in both BASICs, same results. Have raised as an issue as it looks like they are implemented at least partially in console.asm

- print chr$(147) homes the cursor but does not blank the screen.
- print chr$(5) [white] and print chr$(30) [green] do not do anything e.g. text colour does not change.

**Comment by ghackwrench** [comment]
Fixed; also, since CTRL-E isn't as important now that CR doesn't clear to EOL, chr$(5) also works.
