### ISSUE TITLE
Initialise code GLUTs

### ISSUE THREAD

**Issue by paulscottrobson** [ghackwrench/OpenKERNAL#4]
Wrote this bit of code to set up the GLUTs to sensible values (entry N is BBGGRR in 64 bit colour). User can still change it but sets up a workable base.

InitialiseGraphicsLUT:
		inc 	1 							; access I/O page 1 (was called from p0)
		lda 	#$D0 						; point zTemp0 to GLUT Memory
		sta 	zTemp0+1
		stz 	zTemp0
_IGLoop:
		lda 	zTemp0  					; use bits 76 54 32 of address to make RGB colour						
		jsr		IGLShiftWrite1				
		jsr		IGLShiftWrite1				
		jsr		IGLShiftWrite1				
		lda 	#$FF 						; Alpha $FF
		sta 	(zTemp0)
		jsr 	IGLBumpzTemp0
		lda 	zTemp0+1 					; until filled all four GLUTs
		cmp 	#$E0
		bne 	_IGLoop
		rts

IGLShiftWrite1:
		pha 								; save current bit pattern
		and 	#$C0 						; isolate MSBs, put in slot
		ora 	#$1F
		sta 	(zTemp0) 					; write to GLUT
		pla 								; restore and shift next bits in.
		asl 	a
		asl 	a
IGLBumpzTemp0: 								; next GLUT slot.
		inc 	zTemp0
		bne 	_IGLExit
		inc 	zTemp0+1
_IGLExit:
		rts						`

**Comment by ghackwrench** [comment]
Implemented with the old rrrgggbb palette.
